# Generated by Django 4.2.11 on 2024-03-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos_paralelos', '0002_eventos_status_alter_eventos_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='status',
            field=models.CharField(choices=[('Pré-Selecione a Lista', 'Lista Pendente de Seleção'), ('Com Patrocinador', 'Lista com Patrocinador'), ('Aprove a Lista', 'Lista Pendente de Aprovação')], default='Pré-Selecione a Lista', max_length=30),
        ),
    ]
