# Generated by Django 4.2.11 on 2024-03-07 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_eventos_paralelos', '0003_alter_eventos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidados',
            name='createUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convidado', to=settings.AUTH_USER_MODEL),
        ),
    ]
