# Generated by Django 4.2.11 on 2024-03-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos_paralelos', '0004_convidados_createuserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidados',
            name='sponsorSelected',
            field=models.BooleanField(default=False),
        ),
    ]
