# Generated by Django 4.2.11 on 2024-03-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos_paralelos', '0005_convidados_sponsorselected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidadosextras',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='convidadosextras',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='convidadosextras',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
