# Generated by Django 4.2.11 on 2024-03-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos_paralelos', '0007_convidados_postselected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='status',
            field=models.CharField(choices=[('Pré-Selecione a Lista', 'Lista Pendente de Seleção'), ('Com Patrocinador', 'Lista com Patrocinador'), ('Aprove a Lista', 'Lista Pendente de Aprovação'), ('Lista concluida', 'Lista concluida')], default='Pré-Selecione a Lista', max_length=30),
        ),
    ]
